### ISSUE TITLE
Altura del Slider

### ISSUE THREAD

**Issue by gregesf** [Bluetide/Configura#2]
El slider debe ajustarse a la altura de la ventana del explorador... la imagen de fondo esta perdiendo la proporción y se ve como aplastada... Verificar demo del template http://deliciousthemes.com/demo/blink/

**Comment by kurai021** [comment]
Las imagenes de fondo en cada sección se ven recortadas cuando cambio el tamaño del viewport, alguna idea de como puedo hacer esto?

**Comment by kurai021** [comment]
cambio de medida del height de px a vw, eso debe solucionar el problema
