### ISSUE TITLE
Verificar los font-size del quote, los iconos a redes sociales del footer, el párrafo, donde pone "Descripción general de Configura...." les un poco más grande que los párrafos normales

### ISSUE THREAD

**Issue by gregesf** [Bluetide/Configura#3]

**Comment by gregesf** [comment]
lleva aplicada una clase "section-intro" verificar demo Blink http://deliciousthemes.com/demo/blink/

**Comment by gregesf** [comment]
También los font-weight de los títulos deben ser 900 y revisar los font-size del teléfono y mail de contacto, debe ser de font-size:55px, para pantallas de más de 1200, después puedes jugar si no entra etc etc.

**Comment by kurai021** [comment]
podrias confirmarme si he realizado todo lo de este issue?
