### ISSUE TITLE
Verificar ancho del content

### ISSUE THREAD

**Issue by gregesf** [Bluetide/Configura#4]
Actualmente el site tiene un  max-width: 970px; que anula el funcionamiento del responsive a resoluciones mayores, el ancho máximo del site debe ser de 1120px, y ya viene preconfirgirado en el template, mediante el uso de la lcase .centered-wrapper y los tags  sections ---- verificar template demo del template http://deliciousthemes.com/demo/blink/

**Comment by kurai021** [comment]
cambiado a 1120px como max-width
